name: Javascript Tests

on:
  schedule:
    - cron: "*/6 * * * *"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Run Jest Tests
        run: npm run jest-test
      
      - name: Upload results
        # Run this step even if the test step ahead fails
        if: "!cancelled()"
        uses: trunk-io/analytics-uploader@main
        with:
          # Path to your test results.
          junit-paths: "tests/jest/*.xml"
          # Provide your Trunk organization slug.
          org-slug: "alexs-org"
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
        continue-on-error: true
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io