name: Javascript Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description:
          The version of `analytics-cli` to use. Defaults to the latest specified in
          `analytis-uploader`.

jobs:
  test:
    runs-on: public-amd64-small

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Run Mocha Tests
        run: npm run mocha-test

      - name: Run Jest Tests
        run: npm run jest-test

      - name: Run Jasmine Tests
        run: npm run jasmine-test

      - name: Run Playwright Tests
        run: npm run playwright-test

      - name: Upload Jest Test Results
        uses: trunk-io/analytics-uploader@main
        # Upload the results even if the tests fail
        if: "!cancelled()"
        with:
          junit-paths: junit.xml
          org-slug: gmbh
          token: ${{ secrets.TRUNK_API_TOKEN }}
        # don't fail this job if the upload fails
        continue-on-error: true